# Generated by Django 4.0.6 on 2022-07-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('Userid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('UserTemp', models.IntegerField(default=19)),
                ('UserHumid', models.IntegerField(default=55)),
                ('Philipshuetoken', models.CharField(max_length=200)),
                ('Smartthingstoken', models.CharField(max_length=200)),
            ],
        ),
    ]
