# Generated by Django 4.0.6 on 2022-07-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Philipshuetoken',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Smartthingstoken',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Userid',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
