# Generated by Django 4.0.6 on 2022-09-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_userdata_philipshuetoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='Userlocation',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Philipshuetoken',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Smartthingstoken',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Userid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
