# Generated by Django 4.0.6 on 2022-09-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_userdata_userlocation_alter_userdata_philipshuetoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Userlocation',
            field=models.CharField(default='종로구', max_length=10),
        ),
    ]
